<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
    <artifactId>process-engine-adapter-camunda-platform-c7-root</artifactId>
    <version>2026.06.3-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <groupId>dev.bpm-crafters.process-engine-examples</groupId>
  <artifactId>process-engine-api-example-root-c7</artifactId>

  <packaging>pom</packaging>
  <name>Example: Camunda 7 Example Parent</name>

  <properties>
    <!-- Never deploy examples -->
    <deploy.skip>true</deploy.skip>
    <gpg.skip>true</gpg.skip>
    <dokka.skip>true</dokka.skip>
  </properties>

  <modules>
    <module>java-common-fixture</module>
    <module>java-c7-embedded</module>
    <module>java-c7-embedded-sb4</module>
    <module>java-c7-remote</module>
    <module>java-c7-remote-sb4</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-api</groupId>
        <artifactId>process-engine-api</artifactId>
        <version>${process-engine-api.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-embedded-spring-boot-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-remote-spring-boot-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-examples</groupId>
        <artifactId>process-engine-api-example-java-c7-common-fixture</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        <version>2.8.17</version>
      </dependency>

    </dependencies>
  </dependencyManagement>

  <dependencies>
  </dependencies>

  <build>
    <!-- configure examples to be an ordinary Java projects -->
    <sourceDirectory>src/main/java</sourceDirectory>
    <testSourceDirectory>src/test/java</testSourceDirectory>

    <plugins>
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>17</source>
          <target>17</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
