<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
    <artifactId>process-engine-adapter-camunda-platform-c7-root</artifactId>
    <version>2026.06.3-SNAPSHOT</version>
  </parent>

  <artifactId>process-engine-adapter-camunda-platform-c7-bom</artifactId>
  <name>BOM: ${project.artifactId}</name>
  <description>Bill of Materials for Process Engine Camunda 7 Adapters.</description>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-embedded-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-embedded-spring-boot-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-remote-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
        <artifactId>process-engine-adapter-camunda-platform-c7-remote-spring-boot-starter</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
